[workspace]
default-members = [
  "crates/server",
]
members = [
  "crates/*",
]

[workspace.dependencies]
cargo-husky = { version = "1.5.0", features = ["precommit-hook", "run-cargo-clippy", "run-cargo-fmt"] }

